#https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties
server:
  port: 8090

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(DpO8lLFPgba+TR0DifGdIw==)
    password: ENC()
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true